name: Terraform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/terraform-github-actions@v1.3.1
        with:
          terraform_version: '1.1.9'

      - name: Initialize Terraform
        run: terraform init

      - name: Build Terraform
        run: terraform fmt